import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="w-full text-center py-12 font-plus-jakarta text-3xl font-bold">
          Hello world! Im Montserrat Font
        </h1>
      </main>
    
      <footer className="">

      </footer>
    </div>
  )
}
